version: '3.1'
services:
    web:
        build: 
            context: .
            dockerfile: web.Dockerfile
        ports:
          - 3000:3000
    proxy:
        build: 
            context: .
            dockerfile: proxy.Dockerfile
        ports:
          - 5000:5000
